# Generated by Django 2.2.6 on 2020-01-24 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, validators=[tweets.models.validate_content]),
        ),
    ]
